---

language: python
cache: pip
addons:
  apt:
    packages:
    - software-properties-common
    - python-pip

install:
  - pip3 install -U ansible
  - pip install ansible-lint
  - ansible-galaxy install --force geerlingguy.repo-epel
  - ansible-galaxy install --force git+https://github.com/deekayen/ansible-role-etckeeper.git,${TRAVIS_COMMIT}

before_script:
  - ansible --version
  - ansible-galaxy --version
  - ansible-galaxy list
  - ansible-lint --version

script:
  - git ls-files | grep yml | grep -v travis | xargs ansible-lint
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check -e 'ansible_python_interpreter=/usr/bin/python3'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
