---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Install ssh-keygen.
  ansible.builtin.package:
    name: openssh-clients
    state: present
  tags:
    - install

- name: Create an SSH key for root in /root/.ssh/id_rsa.
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_bits: "{{ etckeeper_ssh_key_bits }}"
    ssh_key_file: .ssh/id_rsa

- name: Download the root user public key.
  ansible.builtin.fetch:
    src: /root/.ssh/id_rsa.pub
    dest: /tmp/.ssh

- name: Install etckeeper.
  ansible.builtin.package:
    name: etckeeper
    state: present
  tags:
    - install

- name: Setup git remote for etckeeper.
  ansible.builtin.lineinfile:
    path: /etc/etckeeper/etckeeper.conf
    regexp: '^PUSH_REMOTE'
    line: 'PUSH_REMOTE="gitlab"'
  tags:
    - configure

- name: Initialize etckeeper.
  ansible.builtin.command: etckeeper init
  args:
    chdir: /etc
    creates: /etc/.etckeeper

- name: Configure git identity username for upstream commit attribution.
  community.general.git_config:
    name: user.name
    repo: /etc
    scope: local
    value: 'Ansible etckeeper'

- name: Configure git identity email for upstream commit attribution.
  community.general.git_config:
    name: user.email
    repo: /etc
    scope: local
    value: 'root@{{ ansible_fqdn }}'

- name: Create GitLab project in group etckeeper.
  community.general.gitlab_project:
    server_url: "{{ gitlab_server_url }}"
    api_token: "{{ gitlab_ansible_token }}"
    name: "{{ inventory_hostname_short }}"
    group: "{{ gitlab_group if gitlab_group | length > 0 else omit }}"
    issues_enabled: "{{ gitlab_issues_enabled }}"
    snippets_enabled: "{{ gitlab_snippets_enabled }}"
    state: present
    wiki_enabled: "{{ gitlab_wiki_enabled }}"
    validate_certs: true
    visibility: "{{ gitlab_visibility }}"
  connection: local
  become: false
  tags:
    - configure
  notify:
    - Configure etckeeper remote.
  when: gitlab_ansible_token | length > 1

- name: Save the GitLab key to known_hosts.
  ansible.builtin.shell: "ssh-keyscan -t ecdsa -H {{ gitlab_fqdn }} >> /root/.ssh/known_hosts"
  args:
    creates: /root/.ssh/known_hosts
  when: gitlab_ansible_token | length > 1

- name: Create a server-specific deploy key.
  community.general.gitlab_deploy_key:
    api_url: "{{ gitlab_server_url }}"
    api_token: "{{ gitlab_ansible_token }}"
    can_push: true
    project: "etckeeper/{{ inventory_hostname_short }}"
    key: "{{ lookup('file', '/tmp/.ssh/' + inventory_hostname + '/root/.ssh/id_rsa.pub') }}"
    title: "root@{{ inventory_hostname_short }}"
    state: present
  connection: local
  become: false
  tags:
    - configure
  notify:
    - Run etckeeper initial commit.
    - Push etckeeper to the git remote.
  when: gitlab_ansible_token | length > 1
